bikecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('bikes/', views.bikes_index, name='bikes_index'),
  path('bikes/<int:bike_id>/', views.details, name='details'),
  path('bikes/create/', views.BikeCreate.as_view(), name='bikes_create'),
  path('bikes/<int:pk>/update/', views.BikeUpdate.as_view(), name='bikes_update'),
  path('bikes/<int:pk>/delete/', views.BikeDelete.as_view(), name='bikes_delete'),
  path('bikes/<int:bike_id>/add_maintenance/', views.add_maintenance, name='add_maintenance'),
  path('tools/create/', views.ToolCreate.as_view(), name='tools_create'),
  path('tools/<int:pk>/', views.ToolDetail.as_view(), name='tool_detail'),
  path('tools/', views.ToolList.as_view(), name='tool_list'),
  path('tools/<int:pk>/update/', views.ToolUpdate.as_view(), name='tools_update'),
  path('tools/<int:pk>/delete/', views.ToolDelete.as_view(), name='tools_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

TYPES = (
  ('Mountain', 'Mountain'),
  ('Road', 'Road'),
  ('Gravel', 'Gravel'),
)

TASKS = (
  ('LC', 'Lube Chain'),
  ('WF', 'Wash Frame'),
  ('FT', 'Fill Tires'),
  ('CB', 'Check Bearings'),
  ('RB', 'Replace Brake Pads'),
  ('BW', 'Balance Wheels')
)
class Bike(models.Model):
  type = models.CharField(max_length=8, choices=TYPES, default=TYPES[0])
  make = models.CharField(max_length=25)
  model = models.CharField(max_length=25)
  description = models.TextField(max_length=100)
  year = models.IntegerField()

  def __str__(self):
    return self.make

  def get_absolute_url(self):
      return reverse("details", kwargs={"bike_id": self.id})

class Maintenance(models.Model):
  date = models.DateField('Maintenance date')
  task = models.CharField(max_length=2, choices=TASKS, default=TASKS[0][0])
  bike = models.ForeignKey(Bike, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_task_display()} on {self.date}"
  
  class Meta:
    ordering = ['-date']

class Tool(models.Model):
  name = models.CharField(max_length=50)
  use = models.CharField(max_length=50)
  
  def __str__(self):
    return self.name

  def get_absolute_url(self):
      return reverse("tools_detail", kwargs={"pk": self.id})
  

main_app/forms.py
from django.forms import ModelForm
from .models import Maintenance

class MaintenanceForm(ModelForm):
  class Meta:
    model = Maintenance
    fields = ['date', 'task']

main_app/views.py
from ast import Del
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from main_app.forms import MaintenanceForm
from .models import Bike, Tool
from .forms import MaintenanceForm


# Create your views here.

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def bikes_index(request):
  bikes = Bike.objects.all()
  return render(request, 'bikes/index.html', { 'bikes': bikes })

def details(request, bike_id):
  bikes = Bike.objects.get(id=bike_id)
  maintenance_form = MaintenanceForm()
  return render(request, 'bikes/details.html', { 'bike': bikes, 'maintenance_form': maintenance_form })

def add_maintenance(request, bike_id):
  form = MaintenanceForm(request.POST)
  if form.is_valid():
    new_maintenance = form.save(commit=False)
    new_maintenance.bike_id = bike_id
    new_maintenance.save()
  return redirect('details', bike_id=bike_id)
class BikeCreate(CreateView):
  model = Bike
  fields = '__all__'

class BikeUpdate(UpdateView):
  model = Bike
  fields = ['type', 'make', 'description']

class BikeDelete(DeleteView):
  model = Bike
  success_url = '/bikes/'

class  ToolCreate(CreateView):
  model = Tool
  fields = '__all__'

class ToolList(ListView):
  model = Tool

class ToolDetail(DetailView):
  model = Tool

class ToolUpdate(UpdateView):
  model = Tool
  fields = '__all__'
  success_url = '/tools/'

class ToolDelete(DeleteView):
  model = Tool
  success_url = '/tools/'

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

  <h1>About the bike collector</h1>
  <p>This guy likes bikes... a lot.</p>
</body>
</html>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'css/images/other-bike.svg' %}"
  >
  <title>Bike Collector</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="header-logo-container">
      <a href="/"><p>Bike Collector</p></a>
    </div>
    <nav>
      <ul>
        <li><a href="{% url 'bikes_index' %}">All Bikes</a></li>
        <li><a href="{% url 'tool_list' %}">All Tools</a></li>
        <li><a href="{% url 'bikes_create' %}">Add a Bike</li>
        <li><a href="{% url 'tools_create' %}">Add a Tool</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/bikes/details.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" 
  rel="stylesheet" 
/>
<link rel="stylesheet" href="{% static 'css/mcdp.css' %}">
<script 
  src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"
>
</script>
<link rel="stylesheet" type="text/css" href="{% static 'css/details.css' %}" />
<script defer src="{% static 'js/bike-detail.js' %}"></script>
{% endblock %}

{% block content %}

<section class="bike-container">
  <div class="bike-img">
    <img 
      src="{% static 'css/images/bicycle-solid.svg' %}" 
      alt="bike"
    >
  </div>
  <div class="bike-details">
    <h2>A {{ bike.make }} {{ bike.model }} {{ bike.type }} bike from {{ bike.year }}</h2>
    <p>{{ bike.description }}</p>
    <div class="bike-actions">
      <a href="{% url 'bikes_update' bike.id %}" class="btn warn">Edit</a>
      <a href="{% url 'bikes_delete' bike.id %}" class="btn danger">Delete</a>
  </div>
</section>

<div class="maintenance-tool-container">
  <section class="maintenance">
    <div class="subsection-title">
      <h2>Past Maintenance</h2>
  
    </div>
    <h3>Add Maintenance</h3>
<form action="{% url 'add_maintenance' bike.id %}" method="post" class="subsection-content">
  {% csrf_token %}
  {{ maintenance_form.as_p }}
  <button type="submit" class="btn submit">Add Maintenance</button>
</form>
{% if bike.maintenance_set.all.count %}
    <table>
      <thead>
        <tr><th>Date</th><th>Task</th></tr>
      </thead>
      <tbody>
        {% for maintenance in bike.maintenance_set.all %}
          <tr>
            <td>{{maintenance.date}}</td>
            <td>{{maintenance.get_task_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="subsection-content">
      <p> Your {{bike.make}} {{bike.model}} hasn't had any maintence done.</p>
  </section>
</div>
{% endif %}


{% endblock %}

main_app/templates/bikes/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bike-index.css' %}"/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Bike List</h1>
</section>

<section class="card-container">
  {% for bike in bikes %}
    <div class="card">
      <a href="{% url 'details' bike.id %}">
      <div class="card-content">
        <div class="card-img-container">
          <img 
            src="{% static 'css/images/other-bike.svg' %}" 
            alt="A skater boy cat"
          >
        </div>
        <h2 class="card-title">{{ bike.make }}</h2>
          <p>{{ bike.model }}</p>
          <p>A {{ bike.type }} bike.</p>
        <p><small>{{ bike.description }}</small></p>
      </div>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container">
  <div class="bike-container">
    <img src="{% static 'css/images/bicycle-solid.svg' %}" alt="The Cat Collector Cat" />
  </div>
  <h1>Bikes Galore!<h1>
</section>

{% endblock %}

main_app/templates/main_app/bike_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Bike?</h1>
  <img src="{% static 'css/images/bicycle-solid.svg' %}" alt="Bike"
</div>
<h2>Are you sure you want to delete this {{ object.make }} {{ object.model }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a href="{% url 'details' bike.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/bike_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"
{% endblock%}

{% block content %}

  {% if object %}
    <h1>Edit {{object.model}}</h1>
  {% else %}
    <h1>Add a Bike</h1>
  {% endif %}

<div class="page-header">
  <img src="{% static 'css/images/bicycle-solid.svg' %}"
</div>
<form action="" method="post" class="form-container">
  {% csrf_token %} 
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/tool_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Tool?</h1>

</div>
<h2>Are you sure you want to delete this {{ object.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'tool_detail' tool.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/tool_detail.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/tool-detail.css' %}"
/>
{% endblock %}

{% block content %}
  
<div class="card" >
  <div class="card-bg" ></div>
  <div class="card-content">
    <h2>{{ tool.name }}</h2>
    <p>{{ tool.use }}</p>
  </div>
</div>
<a href="{% url 'tools_update' tool.id %}" class="btn warn">Edit</a>
<a href="{% url 'tools_delete' tool.id %}" class="btn danger">Delete</a>

{% endblock %}

main_app/templates/main_app/tool_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}
<div class="page-header">
  {% if object %}
    <h1>Edit {{object.name}}</h1>
  {% else %}
    <h1>Add a Tool</h1>
  {% endif %}

</div>
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/tool_list.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/tool-list.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>All Tools</h1>
</section>

<section class="card-container">
  {% for tool in tool_list %}
  <div class="card">
    <div class="card-bg" ></div>
    <a href="{% url 'tool_detail' tool.id %}">
      <div class="card-content">
        <h2>{{ tool.name }}</h2>
        <p>{{ tool.use }} </p>
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}